### ISSUE TITLE
Please comment in THIS Issue!

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/github-for-developers#1]
It can be anything you like. This lets us collect everyone's username, which makes it easier to add everyone as a collaborator (i.e. give them write access) to this repo. Thanks!

**Comment by renjithd** [comment]
renjithd

**Comment by vigneshbalan** [comment]
Comment from Vignesh

**Comment by susam** [comment]
This is a _cool_ **comment**.

**Comment by manish1976** [comment]
test comment manish

**Comment by abhayrk** [comment]
This is a comment :)

**Comment by akshayurdh** [comment]
Added one more

**Comment by manish1976** [comment]
comment by manish

**Comment by renjithd** [comment]
<b>bold</b>

**Comment by raopreet** [comment]
hi

**Comment by Randhir123** [comment]
Hello

**Comment by nirmalyaece24** [comment]
Hello

**Comment by drajvanshy** [comment]
hello

**Comment by amitnanda83** [comment]
this is a comment

**Comment by sunainapai** [comment]
**Hey**

**Comment by Vikas148176** [comment]
hello

**Comment by ghost** [comment]
Hello

**Comment by janars2** [comment]
Good morning all.

**Comment by rabhat** [comment]
rabhat

**Comment by Akash2351** [comment]
Hello everyone :)

**Comment by gayatri007** [comment]
Hello..:)

**Comment by NandiniMB** [comment]
Hello !!!

**Comment by bhasub** [comment]
Hello world !

**Comment by githubteacher** [comment]
:tada: @renjithd, @vigneshbalan, @susam, @manish1976, @abhayrk, @akshayurdh, @manish1976, @renjithd, @raopreet, @Randhir123, @nirmalyaece24, @drajvanshy, @amitnanda83, @sunainapai, @Vikas148176, @abhi1206, @janars2, @rabhat, @Akash2351, @gayatri007, and @NandiniMB are now  repository collaborators. :balloon:

**Comment by sinhan41** [comment]
sinhan41

**Comment by malepp** [comment]
malepp

**Comment by anoosharai** [comment]
anoosha

**Comment by githubteacher** [comment]
:tada: @bharathiraja-subramanian, @sinhan41, @malepp, and @anoosharai are now  repository collaborators. :balloon:

**Comment by baveeshna** [comment]
comment

**Comment by jineshmd** [comment]
jineshmd

**Comment by susam** [comment]
It is :umbrella: in Bangalore.

**Comment by githubteacher** [comment]
:tada: @baveeshna and @jineshmd are now  repository collaborators. :balloon:

**Comment by kumark19** [comment]
kumark19

**Comment by githubteacher** [comment]
:tada: @kumark19 is now a repository collaborator. :balloon:

**Comment by bharathphatak** [comment]
Hi

**Comment by sunilmeena02** [comment]
hello

**Comment by bssanjay** [comment]
Sanjay B

**Comment by githubteacher** [comment]
:tada: @bharathphatak, @sunilmeena02, and @bssanjay are now  repository collaborators. :balloon:

**Comment by mattas1** [comment]
Hi

**Comment by vallurisathish** [comment]
@vallurisathish

**Comment by vikaskulkarnirsa** [comment]
vikas

**Comment by patelp23** [comment]
@manish1976  
This is test comment.

**Comment by patelp23** [comment]
#18 Save Bangalore

**Comment by githubteacher** [comment]
:tada: @mattas1, @vallurisathish, @vikaskulkarnirsa, @patelp23, and @patelp23 are now  repository collaborators. :balloon:

**Comment by thejasvijr** [comment]
Bad traffic in Bangalore :(

**Comment by srivas2** [comment]
Commented.

**Comment by ghoserupam** [comment]
Hello everyone

**Comment by srivas2** [comment]
I can't create branch, Please give me write access.

**Comment by githubteacher** [comment]
:tada: @thejasvijr, @srivas2, @ghoserupam, and @srivas2 are now  repository collaborators. :balloon:

**Comment by PreethiKiruba** [comment]
@githubteacher please add me as well.

**Comment by thejaswiK** [comment]
Hello

**Comment by devi504** [comment]
@githubteacher please add me

**Comment by githubteacher** [comment]
:tada: @PreethiKiruba, @thejaswiK, and @devi504 are now  repository collaborators. :balloon:

**Comment by mattas1** [comment]
Good Morning...

**Comment by NandiniMB** [comment]
@githubteacher  please add me as collaborator
