### ISSUE TITLE
CRLF

### ISSUE THREAD

**Issue by bhasub** [githubteacher/github-for-developers#143]
To handle crlf issues, does setting "\* text=auto" in .gitattributes takes care of having uniform line breaks when collaborators use different platforms to check in the code?

**Comment by patrickmckenna** [comment]
@bharathiraja-subramanian For Windows, type `git config --global core.autocrlf true`. For Linux and OS X, type `git config --global core.autocrlf input`.

**Comment by bhasub** [comment]
Developers use both windows and mac here, in that we should not have gitattributes in remote repository?
