### ISSUE TITLE
Please share session recordings

### ISSUE THREAD

**Issue by Vikas148176** [githubteacher/github-for-developers#154]
Hi Patrick ( @patrickmckenna & @githubteacher ),

Please share "RSA • GitHub for Developers" session recording with us for reference.
Session was conducted last week :
Tue, Nov 24, 2015 9:00 AM - 12:00 PM IST
Wed, Nov 25, 2015 9:00 AM - 12:00 PM IST

Regards,
Vikas

**Comment by Vikas148176** [comment]
:+1:

**Comment by Vikas148176** [comment]
Saw https://github.com/githubteacher/github-for-developers/issues/153 after creating this issue.

**Comment by patrickmckenna** [comment]
@Vikas148176 :+1: Thanks for understanding. We should have that ready for you shortly.

**Comment by Vikas148176** [comment]
@patrickmckenna : any ETA ?

**Comment by patrickmckenna** [comment]
@Vikas148176 Hm, we emailed the links to Immanuel 6 days ago. Would you mind asking him?

**Comment by Vikas148176** [comment]
@patrickmckenna : sorry, my bad. Missed that email. Good day.
