### ISSUE TITLE
Github vs Git

### ISSUE THREAD

**Issue by bhasub** [githubteacher/github-for-developers#27]
Is github a GUI client for git with more collaboration tools or is there more than that?

**Comment by susam** [comment]
As far as I understand, GitHub is a web application written using Ruby on Rails (and probably Erlang for backend) that internally uses git to manage our repositories.

It would be interesting to know what @githubteacher has to tell us about this. Please provide as much internal details as possible. Especially, what does GitHub provide extra on top of Git? For example, are pull requests something that is purely implemented in GitHub but not available in git?
