### ISSUE TITLE
Fix Bangalore weather

### ISSUE THREAD

**Issue by susam** [githubteacher/github-for-developers#4]
When does the issue occur: When I go out of :house:.

Observed result: Bangalore is :cloud:-y. It is :umbrella: a lot.

Expected result: Bangalore should be :sunny:.

Please fix it ASAP. This is a critical issue for me.

If it takes too long to fix it, please at least provide :rainbow: as a workaround.

**Comment by NandiniMB** [comment]
Need fix traffic too :)

**Comment by akshayurdh** [comment]
+1

**Comment by ghost** [comment]
- Like  :)

**Comment by rabhat** [comment]
Not in scope..will be fixed in next release :)

**Comment by anoosharai** [comment]
@akshayurdh :smiley:

**Comment by mattas1** [comment]
Also fix Traffic :)
